### ISSUE TITLE
[Bug report]项目无法启动，界面报错

### ISSUE THREAD

**Issue by chenfengyanyu** [chatbookai/ai-to-pptx#1]
前端项目和后端项目启动后，页面报错，信息如下：
```
Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at index.vue:34:32
    at callWithErrorHandling (chunk-3KNGYJXG.js?v=9d917238:1841:32)
    at ReactiveEffect.getter [as fn] (chunk-3KNGYJXG.js?v=9d917238:3343:22)
    at ReactiveEffect.run (chunk-3KNGYJXG.js?v=9d917238:1396:23)
    at job (chunk-3KNGYJXG.js?v=9d917238:3400:32)
    at doWatch (chunk-3KNGYJXG.js?v=9d917238:3442:7)
    at watch (chunk-3KNGYJXG.js?v=9d917238:3275:10)
    at setup (index.vue:34:1)
    at callWithErrorHandling (chunk-3KNGYJXG.js?v=9d917238:1841:18)
    at setupStatefulComponent (chunk-3KNGYJXG.js?v=9d917238:8115:25)
```
辛苦作者帮忙确认下是否遗漏了什么配置，谢谢！

**Comment by chatbookai** [comment]
目前还达不到测试的程度,请两周以后再测试,到时候会单独通知你
