### ISSUE TITLE
[Bug report] 项目界面未能正常渲染

### ISSUE THREAD

**Issue by zhenzi0322** [chatbookai/ai-to-pptx#4]
```
index.vue:34 
 Uncaught 
TypeError: Cannot read properties of undefined (reading 'id')
    at index.vue:34:32
    at callWithErrorHandling (runtime-core.esm-bundler.js:188:32)
    at ReactiveEffect.getter [as fn] (runtime-core.esm-bundler.js:1857:22)
    at ReactiveEffect.run (reactivity.esm-bundler.js:170:19)
    at job (runtime-core.esm-bundler.js:1914:31)
    at doWatch (runtime-core.esm-bundler.js:1956:7)
    at watch (runtime-core.esm-bundler.js:1789:10)
    at setup (index.vue:34:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:188:18)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7577:25)
```

**Comment by chatbookai** [comment]
项目还没有正式发布
